apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
namespace: dev-ns
commonLabels:
  variant: dev
# patchesStrategicMerge:
resources:
  - configmap.yaml
  - secret.yaml
bases:
  - ../base
